# Generated by Django 3.1.2 on 2020-11-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsBlog', '0003_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.CharField(blank=True, default='WLUHO9A_xik', help_text='ONLY UNSPLASH IMAGE_IDS', max_length=50),
        ),
    ]
