# Generated by Django 3.1.3 on 2020-12-10 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsBlog', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
    ]
