# Generated by Django 3.1.4 on 2021-04-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsBlog', '0008_auto_20201210_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.CharField(blank=True, default='WLUHO9A_xik', help_text='ONLY PHOTOS UPLOADED TO SERVER!!', max_length=50),
        ),
    ]
